### PR TITLE
Add tiered jitting support for jitbench runs and switch to stable branch

### PR DESCRIPTION
**Pull request by davmason**
This PR ports the changes @noahfalk had in #16. I have since changed the script so it can't be merged automatically.

Also, it contains a switch to the stable jitbench branch. Hopefully this will make our runs work for a while as the dev branch of jitbench has been down for a few days

@lt72 @DrewScoggins

### CODE REVIEW

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Comment by DrewScoggins** [comment]
You probably want to use test ci please, and then kick off the runs manually in the GenPRTest folder, since you have groovy changes.

**Comment by davmason** [comment]
@DrewScoggins I launched a build but it failed complaining that it couldn't find a revision to build. Have you seen this before?

https://ci2.dot.net/job/dotnet_perf-infra/job/stability/job/master/job/GenPRTest/job/generator_prtest/18/console

**Comment by DrewScoggins** [comment]
Just use test ci please to launch the generation.  It is a pain to try and get the parameters right when you do a launch of the job through the Jenkins UI.

**Comment by davmason** [comment]
test ci please

**Pull request merged**
