### PR TITLE
There was a missing part of the dotnet publish command, which caused our runs to not use crossgen libraries and had a major perf impact.

### PR DESCRIPTION
**Pull request by davmason**
@DrewScoggins can you launch a test run on this?

/CC @lt72

### CODE REVIEW

**Comment by DrewScoggins** [comment]
test Windows_NT_JitBenchStart perf

**Comment by DrewScoggins** [comment]
test Windows_NT_JitBenchStart perf

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Comment by lt72** [comment]
LGTM

**Comment by lt72** [comment]
test Windows_NT_JitBenchStart perf

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Comment by lt72** [comment]
test Windows_NT_JitBenchStart perf

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Comment by davmason** [comment]
I had to merge Ryan's changes into my fork of JitBench. Hopefully this is the time it will actually get results.

**Comment by lt72** [comment]
test Windows_NT_JitBenchStart perf

**Comment by lt72** [comment]
LGTM. Please start a test and then you can merge. We should see the request time go down to previous value range...

**Comment by davmason** [comment]
test Windows_NT_JitBenchStart perf

**Pull request merged**
