### PR TITLE
Add Tiered Compilation to JitBench

### PR DESCRIPTION
**Pull request by noahfalk**
This adds a second set of measurements to the JitBench scenario test with COMPLUS_EXPERIMENTAL_TieredCompilation=1.
I also added a new "--setupjitbench False" argument that helped me test my change more quickly. Its a quick and dirty thing so if anyone doesn't like it we can delete that part, but I don't want spend effort improving it further when it appears all this code will be soon replaced.

### CODE REVIEW

**Comment by noahfalk** [comment]
@dotnet-bot help

**Comment by noahfalk** [comment]
test ci please

**Comment by noahfalk** [comment]
@brianrob @davmason - I just kicked off the CI but I'm heading off to bed. Not sure if I'll get time to finish this before I leave for China, but take a look if you get the chance. Thanks!

(If everything worked you aren't going to see tiered jitting run any faster, there is a separate bug I need to fix in coreclr for that)

**Comment by davmason** [comment]
Looks good to me. We just have to coordinate with @DrewScoggins for the changed names of the output files

**Comment by noahfalk** [comment]
Does that mean we need to wait until Drew returns in order to check it in? (which is fine if so)

**Comment by DrewScoggins** [comment]
test ci please

**Comment by davmason** [comment]
This was done in #33. Closing this one.

**Pull request closed without merging**
